apiVersion: v1
kind: ConfigMap
metadata:
  name: s3proxy-nginx-conf
data:
  nginx.conf: |
    worker_processes  3;
    pid /tmp/nginx.pid; # Changed from /var/run/nginx.pid
    error_log  /var/log/nginx/error.log;
    events {
      worker_connections  1024;
    }
    http {
      client_max_body_size 1G;
      server {
          listen       8080;
          server_name  _;

          location ~ ^/(index.html|explorer.css|explorer.js)$ {
              include  /etc/nginx/mime.types;
              root   html;
              index  index.html index.htm;
          }

          location ~ ^/s3/(|index.html|explorer.css|explorer.js)$ {
              include  /etc/nginx/mime.types;
              root   html;
              index  index.html index.htm;
          }

          location / {
             proxy_set_header X-Real-IP $remote_addr;
             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
             proxy_set_header X-Forwarded-Proto $scheme;
             proxy_set_header Host $http_host;

             proxy_connect_timeout 300;
             # Default is HTTP/1, keepalive is only enabled in HTTP/1.1
             proxy_http_version 1.1;
             proxy_set_header Connection "";
             chunked_transfer_encoding off;
             proxy_pass http://0.0.0.0:9000;
          }
      }
    }
